version: '3'

services:
  ams_mvc:
    build: .
    ports: ['8080:80']
    depends_on: ['postgresql']
    links: ['postgresql']
  postgresql:
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
